### ISSUE TITLE
fail to run the demo/daq_3d1d.py with FileExistsError: [Errno 17] 

### ISSUE THREAD

**Issue by luogyong** [MiroK/fenics_ii#7]
Dear MiroK,

I configured a Conda environment on Ubuntu 22.04 (WSL2) and attempted to execute your demo/daq_3d1d.py, but it was unsuccessful. Could you provide any advice on resolving this issue? I would greatly appreciate it. The Python version I'm using is 3.12.1. Here is the error message:

/home/gyluo/cbc.block/src/block/splitting.py:14: SyntaxWarning: invalid escape sequence '\s'
  """Split the form.
Missing HsMG for fract norm computing
/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
Traceback (most recent call last):
  File "/home/gyluo/fenics_ii/demo/daq_3d1d.py", line 9, in <module>
    from xii import *
  File "/home/gyluo/.local/lib/python3.12/site-packages/xii/__init__.py", line 2, in <module>
    from xii.assembler import *
  File "/home/gyluo/.local/lib/python3.12/site-packages/xii/assembler/__init__.py", line 4, in <module>
    from . restriction_form import Restriction
  File "/home/gyluo/.local/lib/python3.12/site-packages/xii/assembler/restriction_form.py", line 3, in <module>
    from xii.meshing.subdomain_mesh import SubDomainMesh
  File "/home/gyluo/.local/lib/python3.12/site-packages/xii/meshing/__init__.py", line 2, in <module>
    from .embedded_mesh import EmbeddedMesh, OuterNormal, InnerNormal, TangentCurve, Skeleton
  File "/home/gyluo/.local/lib/python3.12/site-packages/xii/meshing/embedded_mesh.py", line 5, in <module>
    from .make_mesh_cpp import make_mesh
  File "/home/gyluo/.local/lib/python3.12/site-packages/xii/meshing/make_mesh_cpp.py", line 79, in <module>
    module = compile_cpp(code)
             ^^^^^^^^^^^^^^^^^
  File "/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/dolfin/jit/pybind11jit.py", line 58, in compile_cpp_code
    params['build']['include_dirs'] = dolfin_pc["include_dirs"] + extra_include_dirs + get_pybind_include() + [sysconfig.get_config_var("INCLUDEDIR") + "/" + pyversion]
                                                                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/dolfin/jit/__init__.py", line 16, in get_pybind_include
    return [pybind11.get_include(True), pybind11.get_include()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/pybind11/__init__.py", line 26, in get_include
    dist_cobj.finalize_options()
  File "/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/setuptools/command/install.py", line 55, in finalize_options
    orig.install.finalize_options(self)
  File "/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/setuptools/_distutils/command/install.py", line 462, in finalize_options
    self.create_home_path()
  File "/home/gyluo/anaconda3/envs/fenicsproject/lib/python3.12/site-packages/setuptools/_distutils/command/install.py", line 689, in create_home_path
    os.makedirs(path, 0o700)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/home/gyluo/anaconda3/envs/fenicsproject/bin/python3.12'

**Comment by MiroK** [comment]
Hi could you pay here your conda environment file. I can't reproduce your error with my setup. Also, are you able to run fenics?

**Comment by luogyong** [comment]
Dear Dr. Miroslav

Thank you for your prompt response.

yes. I can run the fenics example sush as poisson.py (people.sc.fsu.edu/~jburkardt/fenics_src/poisson/poisson.py) without any problem. 
My conda environment file is attached below.

name: fenicsproject
channels:
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alabaster=0.7.16=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - astroid=3.0.2=py312h7900ff3_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - binutils_impl_linux-64=2.40=hf600244_0
  - binutils_linux-64=2.40=hbdbef99_2
  - black=24.1.1=py312h7900ff3_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.26.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py312hf06ca03_0
  - chardet=5.2.0=py312h7900ff3_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - cmake=3.28.2=hcfe8598_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - cookiecutter=2.5.0=pyhca7485f_0
  - cryptography=42.0.2=py312h4742d6a_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.0=py312h30efb56_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docstring-to-markdown=0.13=pyhd8ed1ab_0
  - docutils=0.20.1=py312h7900ff3_3
  - eigen=3.4.0=h00ab1b0_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fenics=2019.1.0=py312h3fe2952_42
  - fenics-dijitso=2019.1.0=pyhd8ed1ab_39
  - fenics-dolfin=2019.1.0=py312hcd149c5_42
  - fenics-ffc=2019.1.0=pyhd8ed1ab_39
  - fenics-fiat=2019.1.0=pyhd8ed1ab_39
  - fenics-libdolfin=2019.1.0=h25c491d_42
  - fenics-ufl=2019.1.0=pyhd8ed1ab_16
  - fftw=3.3.10=mpi_mpich_h5537406_8
  - flake8=6.1.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gcc_impl_linux-64=12.3.0=he2b93b0_5
  - gcc_linux-64=12.3.0=h76fc315_2
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.78.3=hfc55251_0
  - glib-tools=2.78.3=hfc55251_0
  - gmp=6.3.0=h59595ed_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.9=h8e1006c_0
  - gstreamer=1.22.9=h98fc4e7_0
  - gxx_impl_linux-64=12.3.0=he2b93b0_5
  - gxx_linux-64=12.3.0=h8a814eb_2
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf5=1.14.3=mpi_mpich_ha2c2bf8_0
  - hypre=2.28.0=mpi_mpich_h716cb5e_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.0=pyhd33586a_0
  - ipython=8.21.0=pyh707e725_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=1.0.3=py312h4b3b743_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py312h7900ff3_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyring=24.3.0=py312h7900ff3_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.2=h59595ed_1
  - libblas=3.9.0=21_linux64_openblas
  - libboost=1.82.0=h6fcfa73_6
  - libboost-headers=1.84.0=ha770c72_0
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=21_linux64_openblas
  - libclang=15.0.7=default_hb11cfb5_4
  - libclang13=15.0.7=default_ha2b6cf4_4
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-devel_linux-64=12.3.0=h8bca6fd_105
  - libgcc-ng=13.2.0=h807b86a_5
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.3=h783c2da_0
  - libgomp=13.2.0=h807b86a_5
  - libgpg-error=1.47=h71f35ed_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.42=h2797004_0
  - libpq=16.1=h33b98f1_7
  - libsanitizer=12.3.0=h0f45ef3_5
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=12.3.0=h8bca6fd_105
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=255=h3516f8a_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.3.2=h658648e_1
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.4=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.4=py312h98912ed_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - metis=5.1.0=h59595ed_1007
  - mistune=3.0.2=pyhd8ed1ab_0
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - mpfr=4.2.1=h9458935_0
  - mpg123=1.32.4=h59595ed_0
  - mpi=1.0=mpich
  - mpi4py=3.1.5=py312h5256a87_0
  - mpich=4.1.2=h846660c_103
  - mpmath=1.3.0=pyhd8ed1ab_0
  - mumps-include=5.2.1=ha770c72_11
  - mumps-mpi=5.2.1=h7ee95aa_11
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.14.2=pyhd8ed1ab_0
  - nbconvert-core=7.14.2=pyhd8ed1ab_0
  - nbconvert-pandoc=7.14.2=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py312h06a4308_0
  - nspr=4.35=h27087fc_0
  - nss=3.97=h1d7d5a4_0
  - numpy=1.26.3=py312heda63a1_0
  - numpydoc=1.6.0=pyhd8ed1ab_0
  - openssl=3.2.1=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandoc=3.1.3=h32600fe_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmetis=4.0.3=h2a9763c_1005
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.42=hcad00b1_0
  - petsc=3.20.2=real_h622a54c_100
  - petsc4py=3.20.2=real_h098918d_100
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - pkgconfig=1.5.5=pyhd8ed1ab_4
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312h98912ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptscotch=6.0.9=hb499603_2
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-global=2.11.1=py312h8572e83_2
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.1.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pylint=3.0.3=pyhd8ed1ab_0
  - pylint-venv=3.0.3=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - pyqtwebengine=5.15.9=py312hbd9a932_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.1=hab00c5b_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.1.2=pyhd8ed1ab_0
  - python-lsp-server=1.9.0=pyhd8ed1ab_0
  - python-lsp-server-base=1.9.0=pyhd8ed1ab_0
  - python-slugify=8.0.3=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytz=2023.4=pyhd8ed1ab_0
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - pyzmq=25.1.2=py312h886d080_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.8=h450f30e_18
  - qt-webengine=5.15.8=h7517aa4_5
  - qtawesome=1.3.0=pyh9208f05_0
  - qtconsole=5.5.1=pyhd8ed1ab_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - referencing=0.33.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rhash=1.4.4=hd590300_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rope=1.12.0=pyhd8ed1ab_0
  - rpds-py=0.17.1=py312h4b3b743_0
  - rtree=1.2.0=py312hb0aae1a_0
  - scalapack=2.2.0=hd931219_1
  - scotch=6.0.9=hb2e6521_2
  - secretstorage=3.3.3=py312h7900ff3_2
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.16.0=pyh6c4a22f_0
  - slepc=3.20.1=real_hac23e11_100
  - slepc4py=3.20.1=real_h421bb0b_100
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.8=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.5=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - spyder=5.5.0=py312h7900ff3_3
  - spyder-kernels=2.5.0=unix_pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - suitesparse=5.10.1=h5a4f163_3
  - superlu=5.2.2=h00795ac_0
  - superlu_dist=7.2.0=h25dcc4a_0
  - swig=4.2.0=h1bc8f3f_1
  - sympy=1.12=pyh04b8f61_3
  - sysroot_linux-64=2.12=he073ed8_16
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.11.0=h00ab1b0_1
  - text-unidecode=1.3=pyhd8ed1ab_1
  - textdistance=4.5.0=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - tornado=6.3.3=py312h98912ed_1
  - traitlets=5.14.1=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.20240106=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h0c530f3_0
  - ujson=5.9.0=py312h30efb56_0
  - urllib3=2.2.0=pyhd8ed1ab_0
  - watchdog=3.0.0=py312h7900ff3_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - whatthepatch=1.0.5=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - wurlitzer=3.0.3=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.40=hd590300_0
  - xorg-compositeproto=0.4.2=h7f98852_1001
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.40.1=pyhd8ed1ab_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - block==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.47.2
      - haznics==1.0.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - pillow==10.2.0
      - pybind11==2.2.4
      - pyparsing==3.1.1
      - scipy==1.12.0
prefix: /home/gyluo/anaconda3/envs/fenicsproject



***@***.***
 
From: Miroslav Kuchta
Date: 2024-02-03 03:41
To: MiroK/fenics_ii
CC: luogyong; Author
Subject: Re: [MiroK/fenics_ii] fail to run the demo/daq_3d1d.py with FileExistsError: [Errno 17] (Issue #7)
Hi could you pay here your conda environment file. I can't reproduce your error with my setup. Also, are you able to run fenics?

**Comment by luogyong** [comment]
At last, I discovered that the issue stems from pybind11. Specifically, the include folder is missing in the pybind11 directory. To resolve this, I reinstalled it using the script below:
1) git clone https://github.com/pybind/pybind11.git
2) cd pybind11
3) pip install .
4) export PYBIND11_DIR=<pathto>/pybind11/

**Comment by MiroK** [comment]
Great and thanks for debugging!
